### PR TITLE
Completed BeaconStatus.cpp

### PR DESCRIPTION
**Pull request by niwhsa9**
- Implemented int32/float conversions in constructor
- Added output in attr = value format 
- Uncommented Beacon Tests in CMakeLists.txt
- Fixed minor syntax error (missing semicolons) in BeaconDecoderTest 

I think I did what you asked. However, I am not sure if I was supposed to switch the byte order with 'nthol' on all the attributes or just the gyro/mag values. Let me know.

I did notice a bug when running the beacon test where the gyro test failed despite having returned the correct value. I've attached an image below: 

Rounding error maybe?

### CODE REVIEW

**Review by mark64 — APPROVED** [review]
Looks good. 
As for the gyro issue, you can trying getting the absolute value of the difference between the desired value and the measured value and comparing it to a predefined tolerance with ASSERT_LT.

**Comment by niwhsa9** [comment]
Ok thanks. I'll probably threshold it like you described. I just wanted to make sure everyone is okay with that.

**Comment by mcli** [comment]
Hey Ashwin,

Can you make the attributes without spaces in them?  Replace spaces with "_", for example.  The ground processing expects attribute=value pairs, and won't like the spaces.

Thanks,

-Maurice

**Comment by niwhsa9** [comment]
Alright, I changed it. Is that okay? There is still technically whitespace in there since there is an std::endl separating the elements. I assume the ground station uses the endline as the delimiter?

**Comment by mcli** [comment]
magnetorquer, voltage, current, and temperature measurements should all be converted to real values and have associated unit tests...

**Comment by mcli** [comment]
Hey Ashwin, can you create a pull request to merge into the dev branch instead of master?

**Comment by niwhsa9** [comment]
I take it its okay to merge to dev for testing code, even if not completed?

**Pull request merged**
